import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Container from "@/components/container/Container";
import localFont from "next/font/local";
import Footer from "@/components/footer/Footer";

const rubik = localFont({
  src: [
    {
      path: "../../public/fonts/Rubik.ttf",
      weight: "400",
    },
  ],
});
export const metadata: Metadata = {
  title: {
    default: "adel Shop",
    template: "adel Shop | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={rubik.className}>
        <Container>
          <Navbar />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
